'use strict';
const page=document.body.dataset.page;
const nav=[['produkter','Produkter'],['dokumenter','Dokumentasjon'],['logistikk','Logistikk'],['om-oss','Om Visnes'],['kontakt','Kontakt oss']];
document.getElementById('site-header').innerHTML=`<div class="concept-bar"><div class="wrap"><a href="forslag.html">Om forbedringene</a></div></div><header class="header wrap"><a class="brand" href="index.html" aria-label="Visnes Kalk, forsiden"><img src="assets/logo.svg" width="187" height="58" alt="Visnes Kalk"></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Meny</button><nav class="nav" id="main-nav" aria-label="Hovedmeny">${nav.map(([slug,label])=>`<a href="${slug}.html" ${page===slug?'aria-current="page"':''} class="${slug==='kontakt'?'nav-contact':''}">${label}</a>`).join('')}</nav></header>`;
document.getElementById('site-footer').innerHTML=`<footer class="footer"><div class="wrap"><div class="footer-grid"><div><strong>VISNES KALK AS</strong><p>Visnesvegen 131<br>6493 Lyngstad, Norge</p><p>Marmor og eklogitt fra Nordmøre.</p></div><div><strong>FINN FREM</strong><a href="produkter.html">Produkter</a><a href="dokumenter.html">Dokumentasjon</a><a href="logistikk.html">Logistikk og levering</a><a href="https://www.visneskalk.no/no/avfallsplan-havn" target="_blank" rel="noopener">Avfallsplan havn (dagens nettsted)</a></div><div><strong>TA KONTAKT</strong><a href="tel:+4771299220">+47 71 29 92 20</a><a href="mailto:post@visneskalk.no">post@visneskalk.no</a><a href="https://www.visneskalk.no/en" target="_blank" rel="noopener" lang="en">English · current website</a></div></div><div class="footer-bottom"><span>Org.nr. 979 489 498 · Visnes Kalk AS</span><span><a href="forslag.html" style="display:inline">Vurdering og forbedringer</a></span></div></div></footer>`;
const menu=document.querySelector('.menu-toggle');const menuNav=document.getElementById('main-nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menuNav.classList.toggle('open',open);});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menuNav.classList.contains('open')){menuNav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus();}});
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=value=>String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replaceAll('ø','o').replaceAll('æ','ae').replace(/[\u2013\u2014]/g,'-').replace(/\s/g,'');
const params=new URLSearchParams(location.search);const data=window.VISNES_DATA;
const empty=(label)=>`<div class="empty"><h2>Ingen treff</h2><p>Prøv et annet søkeord eller fjern et filter.</p><button class="button secondary" id="clear-filters">Nullstill ${label}</button></div>`;
const productLink=p=>`produkt.html?id=${encodeURIComponent(p.id)}`;
const productCard=p=>`<a class="product-card" href="${productLink(p)}"><span class="tag">${escapeHTML(p.category)}</span><h2>${escapeHTML(p.name)}</h2><p>${escapeHTML(p.size)}${p.name==='Vassbygging HD Eklogittstein'?' · enhet avklares':''}</p><div class="card-bottom"><span class="badge">${p.url?'Datablad tilgjengelig':'Be om datablad'}</span><strong>Se produkt</strong></div></a>`;
if(page==='produkter'){
 const search=document.getElementById('product-search'),category=document.getElementById('category-select'),results=document.getElementById('product-results');let material='';
 [...new Set(data.products.map(p=>p.category))].forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;category.appendChild(o);});
 category.value=[...category.options].some(o=>o.value===params.get('category'))?params.get('category'):'';search.value=params.get('q')||'';
 function renderProducts(){const q=normalize(search.value);const found=data.products.filter(p=>(!category.value||p.category===category.value)&&(!material||p.material===material)&&normalize(p.name+' '+p.category+' '+p.size+' '+p.material+' '+p.filename).includes(q));document.getElementById('product-count').textContent=`Viser ${found.length} av ${data.products.length} produkter`;results.innerHTML=found.length?found.map(productCard).join(''):empty('filtre');const clear=document.getElementById('clear-filters');if(clear)clear.onclick=()=>{search.value='';category.value='';material='';document.querySelectorAll('[data-material]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.material==='')));renderProducts();search.focus();};}
 search.addEventListener('input',renderProducts);category.addEventListener('change',renderProducts);document.querySelectorAll('[data-material]').forEach(b=>b.addEventListener('click',()=>{material=b.dataset.material;document.querySelectorAll('[data-material]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderProducts();}));renderProducts();
}
if(page==='dokumenter'){
 const search=document.getElementById('document-search'),type=document.getElementById('type-select'),results=document.getElementById('document-results');type.value=[...type.options].some(o=>o.value===params.get('type'))?params.get('type'):'';search.value=params.get('q')||'';
 function renderDocs(){const q=normalize(search.value);const found=data.documents.filter(d=>(!type.value||d.category===type.value)&&normalize(d.title+' '+d.category+' '+d.family+' '+d.filename+' '+(d.category==='Sikkerhetsdatablad'?'HMS SDS sikkerhet':'')).includes(q));document.getElementById('document-count').textContent=`Viser ${found.length} av ${data.documents.length} dokumenter`;results.innerHTML=found.length?found.map(d=>`<tr><td><strong>${escapeHTML(d.title)}</strong><small>${escapeHTML(d.family)}${d.productId?` · <a class="pdf-link" href="produkt.html?id=${encodeURIComponent(d.productId)}">Se produkt</a>`:''}</small></td><td>${escapeHTML(d.category)}<small>${escapeHTML(d.language)} · PDF</small></td><td><a class="pdf-link" href="${escapeHTML(d.url)}" target="_blank" rel="noopener" aria-label="Åpne ${escapeHTML(d.title)} som PDF i ny fane">Åpne PDF</a></td></tr>`).join(''):`<tr><td colspan="3">${empty('filtre')}</td></tr>`;const clear=document.getElementById('clear-filters');if(clear)clear.onclick=()=>{search.value='';type.value='';renderDocs();search.focus();};}
 search.addEventListener('input',renderDocs);type.addEventListener('change',renderDocs);renderDocs();
}
if(page==='produkt'){
 const p=data.products.find(p=>p.id===params.get('id'));const target=document.getElementById('product-detail');
 if(!p){target.innerHTML='<section class="section wrap"><p class="eyebrow">PRODUKTKATALOG</p><h1>Vi fant ikke dette produktet.</h1><p>Gå til katalogen for å velge et produkt.</p><a class="button blue" href="produkter.html">Se alle produkter</a></section>';}
 else{
  document.title=`${p.name} ${p.size} | Visnes Kalk`;
  const summaries={'Jordbrukskalk':'Kalkprodukter for jordbruk og fôr. Finn publisert produktinformasjon og avklar kravene til ditt bruksområde med Visnes.','Vannverksmarmor':'Vannverksmarmor fra Visnes. Se produktdatabladet for detaljer om den valgte graderingen.','Blåsesand':'Marmor til blåsing. Avklar produktvalg og krav til overflaten som skal behandles med Visnes.','Betong/Bygg':'Marmor til bygg og anlegg. Se produktdatabladet og be om relevant ytelseserklæring for den tiltenkte bruken.','Vassdragskalk':'Marmorpulver i klasse 4. Se publiserte produktegenskaper i databladet.','Asfalt filler':'Fillerprodukt fra Visnes. Se produktdatabladet og avklar krav til dokumentasjon for prosjektet.','Eklogitt':'Eklogitt i flere graderinger. Kontakt Visnes for produktdata og avklaring av bruksområde.','Prosessindustri':'Marmorprodukter for prosessindustri. Avklar ønsket gradering og øvrige krav med Visnes.'};
  const safety=data.documents.find(d=>d.category==='Sikkerhetsdatablad'&&d.family===p.material&&d.language==='NO');
  const enquiry=`kontakt.html?product=${encodeURIComponent(p.name+' · '+p.size)}`;
  target.innerHTML=`<section class="page-intro"><div class="wrap"><nav class="breadcrumbs" aria-label="Brødsmuler"><a href="index.html">Forsiden</a><span>/</span><a href="produkter.html">Produkter</a><span>/</span><a href="produkter.html?category=${encodeURIComponent(p.category)}">${escapeHTML(p.category)}</a></nav><p class="eyebrow">${escapeHTML(p.material)} FRA VISNES</p><h1>${escapeHTML(p.name)}</h1><p>${escapeHTML(p.size)}${p.name==='Vassbygging HD Eklogittstein'?' · enhet må avklares med Visnes':''}</p></div></section><section class="content-section wrap"><div class="detail-grid"><div><h2>Om produktet</h2><p>${summaries[p.category]}</p><dl class="spec-list"><dt>Materiale</dt><dd>${escapeHTML(p.material)}</dd><dt>Produktområde</dt><dd>${escapeHTML(p.category)}</dd><dt>Oppgitt gradering</dt><dd>${escapeHTML(p.size)}</dd></dl>${p.name==='Vassbygging HD Eklogittstein'?'<div class="note">Den norske produktlisten oppgir ikke enhet for denne graderingen. Den engelske listen bruker tommer. Bekreft gradering og enhet med Visnes før bestilling.</div>':''}<p class="note">Opplysninger fra den publiserte produktlisten. Produktets egenskaper, egnethet og leveringsmuligheter avklares med Visnes.</p><a class="underlink" href="produkter.html?category=${encodeURIComponent(p.category)}">Flere produkter i ${escapeHTML(p.category)}</a></div><aside class="aside-box"><p class="eyebrow">PRODUKT OG DOKUMENTASJON</p><h2>Dokumenter og kontakt</h2>${p.url?`<a class="button secondary" href="${escapeHTML(p.url)}" target="_blank" rel="noopener">Åpne produktdatablad (PDF)</a>`:`<p>Produktdatablad er ikke lenket i dagens produktliste. Be oss om dokumentasjon for denne graderingen.</p>`}${safety?`<a class="button secondary" href="${escapeHTML(safety.url)}" target="_blank" rel="noopener">Sikkerhetsdatablad (PDF)</a>`:''}<a class="button blue" href="${enquiry}">${p.url?'Spør om dette produktet':'Be om produktdata'}</a><p style="margin-top:20px">Se revisjonsdato og detaljer i originaldokumentet.</p></aside></div></section>`;
 }
}
if(page==='kontakt'){
 document.getElementById('enquiry-product').value=params.get('product')||params.get('subject')||'';
 const form=document.getElementById('enquiry-form');form.addEventListener('submit',e=>{e.preventDefault();const product=document.getElementById('enquiry-product').value.trim(),quantity=document.getElementById('enquiry-quantity').value.trim(),place=document.getElementById('enquiry-location').value.trim(),message=document.getElementById('enquiry-message').value.trim();if(!message){document.getElementById('enquiry-message').setCustomValidity('Skriv hva du trenger hjelp med.');form.reportValidity();return;}document.getElementById('enquiry-message').setCustomValidity('');document.getElementById('email-body').textContent=`Hei Visnes Kalk,\n\n${product?'Produkt / tema: '+product+'\n':''}${quantity?'Mengde: '+quantity+'\n':''}${place?'Leveringssted: '+place+'\n':''}\n${message}`;const preview=document.getElementById('enquiry-preview');preview.hidden=false;preview.focus();document.getElementById('copy-status').textContent='';});
 document.getElementById('enquiry-message').addEventListener('input',e=>e.target.setCustomValidity(''));
 document.getElementById('copy-enquiry').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.getElementById('email-body').textContent);document.getElementById('copy-status').textContent=' Teksten er kopiert.';}catch{document.getElementById('copy-status').textContent=' Marker og kopier teksten over.';}});
}
